# Generated by Django 5.1.4 on 2024-12-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_estudiante_promedio_general_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='estudiantes.estudiante', to_field='documento_identidad'),
        ),
    ]
