# Generated by Django 5.1.4 on 2024-12-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_alter_nota_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(default='Nuevo', max_length=100),
        ),
    ]
